#!/usr/bin/env bash
# =============================================================================
# WSL2: create ~/mycosoft-data (or $MYCOSOFT_DATA_ROOT) and env file for caches/models.
# Run directly or from wsl-gpu-node-setup.sh
# Date: April 15, 2026
# =============================================================================
set -euo pipefail

ROLE="${MYCOSOFT_STORAGE_ROLE:-all}"
AUTO_YES=false
ROOT="${MYCOSOFT_DATA_ROOT:-$HOME/mycosoft-data}"

while [[ $# -gt 0 ]]; do
  case $1 in
    --role) ROLE="$2"; shift 2 ;;
    --root) ROOT="$2"; shift 2 ;;
    --yes|-y) AUTO_YES=true; shift ;;
    *) echo "Usage: $0 [--role earth2|voice|all] [--root PATH] [--yes]"; exit 1 ;;
  esac
done

mkdir -p "$ROOT"/{models/earth2,models/voice,models/shared,weights,cache/huggingface/hub,cache/huggingface/datasets,cache/huggingface/transformers,cache/torch,cache/pip,ollama,data/datasets,memory/embeddings,memory/working,scratch,logs}

cat > "$ROOT/README.txt" <<EOF
Mycosoft WSL data root — $(date -Iseconds)
Role: $ROLE

HF / torch / Ollama paths are exported from env.sh (source from ~/.bashrc).
Use fast NTFS drives via /mnt/d/... if you set MYCOSOFT_DATA_ROOT before re-running this script.
EOF

ENV_FILE="$HOME/mycosoft-data-env.sh"
cat > "$ENV_FILE" <<EOF
# Generated by wsl-mycosoft-data-layout.sh — source from ~/.bashrc
export MYCOSOFT_DATA_ROOT="$ROOT"
export HF_HOME="$ROOT/cache/huggingface"
export HF_HUB_CACHE="$ROOT/cache/huggingface/hub"
export HUGGINGFACE_HUB_CACHE="$ROOT/cache/huggingface/hub"
export HF_DATASETS_CACHE="$ROOT/cache/huggingface/datasets"
export TRANSFORMERS_CACHE="$ROOT/cache/huggingface/transformers"
export TORCH_HOME="$ROOT/cache/torch"
export PIP_CACHE_DIR="$ROOT/cache/pip"
export XDG_CACHE_HOME="$ROOT/cache"
export OLLAMA_MODELS="$ROOT/ollama"
export MYCOSOFT_EARTH2_CHECKPOINTS="$ROOT/models/earth2"
export MYCOSOFT_VOICE_MODELS="$ROOT/models/voice"
export MYCOSOFT_LOCAL_MEMORY="$ROOT/memory"
export HF_HUB_ENABLE_HF_TRANSFER="${HF_HUB_ENABLE_HF_TRANSFER:-1}"
EOF

MARKER="# Mycosoft data layout (added by wsl-mycosoft-data-layout.sh)"
if ! grep -qF "$MARKER" "$HOME/.bashrc" 2>/dev/null; then
  {
    echo ""
    echo "$MARKER"
    echo "if [[ -f \"$ENV_FILE\" ]]; then source \"$ENV_FILE\"; fi"
  } >> "$HOME/.bashrc"
fi

# shellcheck source=/dev/null
source "$ENV_FILE"

echo "[mycosoft-data] Layout ready under: $ROOT"
echo "[mycosoft-data] Sourced: $ENV_FILE (also appended to ~/.bashrc)"
echo "[mycosoft-data] HF_HOME=$HF_HOME"
