import { NextRequest, NextResponse } from "next/server";
import * as fs from "fs";
import * as path from "path";

interface NewAgent {
  agent_id: string;
  name: string;
  display_name: string;
  description: string;
  category: string;
  capabilities: string[];
  keywords: string[];
  voice_triggers: string[];
  requires_confirmation: boolean;
}

// Agent template for generating Python agent code
const AGENT_TEMPLATE = (agent: NewAgent) => `"""
${agent.display_name}

${agent.description}

Auto-generated by MYCA Agent Creator
"""

from typing import Any, Dict, List, Optional
from mycosoft_mas.agents.base_agent import BaseAgent


class ${agent.name}(BaseAgent):
    """${agent.description}"""
    
    def __init__(self):
        super().__init__(
            agent_id="${agent.agent_id}",
            name="${agent.display_name}",
            category="${agent.category}",
            capabilities=${JSON.stringify(agent.capabilities)},
            keywords=${JSON.stringify(agent.keywords)},
            voice_triggers=${JSON.stringify(agent.voice_triggers)},
            requires_confirmation=${agent.requires_confirmation ? "True" : "False"},
        )
    
    async def process(self, task: Dict[str, Any]) -> Dict[str, Any]:
        """Process incoming task.
        
        Args:
            task: Task dictionary containing action and parameters
            
        Returns:
            Result dictionary with status and data
        """
        action = task.get("action", "default")
        params = task.get("params", {})
        
        try:
            if action == "status":
                return await self.get_status()
            elif action == "analyze":
                return await self.analyze(params)
            elif action == "execute":
                return await self.execute_action(params)
            else:
                return {
                    "status": "success",
                    "message": f"${agent.display_name} processed action: {action}",
                    "data": params
                }
        except Exception as e:
            return {
                "status": "error",
                "message": str(e)
            }
    
    async def get_status(self) -> Dict[str, Any]:
        """Get agent status."""
        return {
            "status": "success",
            "agent_id": self.agent_id,
            "name": self.name,
            "state": "active",
            "category": "${agent.category}",
            "capabilities": ${JSON.stringify(agent.capabilities)}
        }
    
    async def analyze(self, params: Dict[str, Any]) -> Dict[str, Any]:
        """Analyze data based on agent's specialty."""
        # TODO: Implement analysis logic
        return {
            "status": "success",
            "message": "Analysis complete",
            "params": params
        }
    
    async def execute_action(self, params: Dict[str, Any]) -> Dict[str, Any]:
        """Execute an action."""
        # TODO: Implement execution logic
        return {
            "status": "success",
            "message": "Action executed",
            "params": params
        }


# Register agent
def get_agent() -> ${agent.name}:
    """Factory function to create agent instance."""
    return ${agent.name}()
`;

export async function POST(request: NextRequest) {
  try {
    const agent: NewAgent = await request.json();
    
    // Validate required fields
    if (!agent.agent_id || !agent.name || !agent.description) {
      return NextResponse.json(
        { error: "Missing required fields: agent_id, name, description" },
        { status: 400 }
      );
    }
    
    // Generate agent code
    const agentCode = AGENT_TEMPLATE(agent);
    
    // Write agent file
    const agentsDir = path.join(process.cwd(), "..", "mycosoft_mas", "agents", "custom");
    
    // Ensure directory exists
    if (!fs.existsSync(agentsDir)) {
      fs.mkdirSync(agentsDir, { recursive: true });
    }
    
    const agentFile = path.join(agentsDir, `${agent.agent_id}.py`);
    fs.writeFileSync(agentFile, agentCode);
    
    // Update registry
    const registryPath = path.join(process.cwd(), "..", "mycosoft_mas", "agents", "registry.json");
    let registry: { agents: NewAgent[] } = { agents: [] };
    
    if (fs.existsSync(registryPath)) {
      const content = fs.readFileSync(registryPath, "utf-8");
      registry = JSON.parse(content);
    }
    
    // Add new agent to registry
    const existingIndex = registry.agents.findIndex(a => a.agent_id === agent.agent_id);
    if (existingIndex >= 0) {
      registry.agents[existingIndex] = agent;
    } else {
      registry.agents.push(agent);
    }
    
    fs.writeFileSync(registryPath, JSON.stringify(registry, null, 2));
    
    return NextResponse.json({
      success: true,
      message: `Agent ${agent.display_name} created successfully`,
      agent_id: agent.agent_id,
      file: agentFile
    });
  } catch (error) {
    console.error("Agent creation error:", error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Failed to create agent" },
      { status: 500 }
    );
  }
}

