#!/bin/bash
# Transfer and execute on Ubuntu control node

echo "=================================================="
echo "MYCA Bootstrap - Ubuntu Transfer Script"
echo "=================================================="
echo ""
echo "Run these commands on your Ubuntu control node:"
echo ""
echo "1. From this Windows machine, copy to Ubuntu:"
echo "   scp -r C:\\Users\\admin2\\Desktop\\MYCOSOFT\\CODE\\MAS\\mycosoft-mas user@ubuntu-ip:~/"
echo ""
echo "2. SSH to Ubuntu:"
echo "   ssh user@ubuntu-ip"
echo ""
echo "3. On Ubuntu, run:"
echo "   cd ~/mycosoft-mas"
echo "   chmod +x infra/myca-online/bootstrap_myca.sh"
echo "   bash infra/myca-online/bootstrap_myca.sh dry-run"
echo "   bash infra/myca-online/bootstrap_myca.sh apply"
echo ""
echo "OR if Ubuntu is this same machine with WSL Ubuntu:"
echo "=================================================="
echo ""
echo "If you have WSL with Ubuntu (not docker-desktop):"
echo "   wsl -d Ubuntu"
echo "   cd /mnt/c/Users/admin2/Desktop/MYCOSOFT/CODE/MAS/mycosoft-mas"
echo "   bash infra/myca-online/bootstrap_myca.sh dry-run"
echo "   bash infra/myca-online/bootstrap_myca.sh apply"
echo ""
