version: '3.8'

services:
  orchestrator-myca:
    build: ../orchestrator-myca
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    restart: always
    depends_on:
      - mongodb

  lab_rnd_agent:
    build: ../agents/lab_rnd_agent
    ports:
      - "8001:8001"
    restart: always
    env_file:
      - ../.env
    depends_on:
      - mongodb

  dev_agent:
    build: ../agents/dev_agent
    ports:
      - "8002:8002"
    restart: always
    env_file:
      - ../.env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
