import { NextResponse } from "next/server";

// Mock flow data - in production, this would fetch from the Python MAS backend
const flows = [
  {
    id: "1",
    source: "MYCA Orchestrator",
    destination: "Financial Agent",
    service: "HTTPS",
    risk: "Low",
    direction: "out",
    inBytes: "4.6 KB",
    outBytes: "1.2 KB",
    action: "Allow",
    timestamp: new Date().toISOString(),
  },
  {
    id: "2",
    source: "MYCA Orchestrator",
    destination: "Mycology Research",
    service: "HTTPS",
    risk: "Low",
    direction: "out",
    inBytes: "2.1 KB",
    outBytes: "0.8 KB",
    action: "Allow",
    timestamp: new Date().toISOString(),
  },
  {
    id: "3",
    source: "Opportunity Scout",
    destination: "External APIs",
    service: "HTTPS",
    risk: "Low",
    direction: "out",
    inBytes: "12.3 KB",
    outBytes: "0.5 KB",
    action: "Allow",
    timestamp: new Date().toISOString(),
  },
  {
    id: "4",
    source: "Project Manager",
    destination: "n8n Workflows",
    service: "HTTP",
    risk: "Low",
    direction: "both",
    inBytes: "8.9 KB",
    outBytes: "3.2 KB",
    action: "Allow",
    timestamp: new Date().toISOString(),
  },
  {
    id: "5",
    source: "Human Operator",
    destination: "MYCA Orchestrator",
    service: "WebSocket",
    risk: "Low",
    direction: "both",
    inBytes: "1.5 KB",
    outBytes: "2.8 KB",
    action: "Allow",
    timestamp: new Date().toISOString(),
  },
  {
    id: "6",
    source: "Financial Agent",
    destination: "PostgreSQL",
    service: "SQL",
    risk: "Low",
    direction: "both",
    inBytes: "15.2 KB",
    outBytes: "0.3 KB",
    action: "Allow",
    timestamp: new Date().toISOString(),
  },
  {
    id: "7",
    source: "Mycology Research",
    destination: "Knowledge Graph",
    service: "GraphQL",
    risk: "Low",
    direction: "both",
    inBytes: "22.1 KB",
    outBytes: "1.1 KB",
    action: "Allow",
    timestamp: new Date().toISOString(),
  },
  {
    id: "8",
    source: "MycoDAO Agent",
    destination: "Blockchain",
    service: "RPC",
    risk: "Low",
    direction: "out",
    inBytes: "0.5 KB",
    outBytes: "4.2 KB",
    action: "Allow",
    timestamp: new Date().toISOString(),
  },
  {
    id: "9",
    source: "Dashboard Agent",
    destination: "User Interface",
    service: "WebSocket",
    risk: "Low",
    direction: "both",
    inBytes: "45.3 KB",
    outBytes: "12.1 KB",
    action: "Allow",
    timestamp: new Date().toISOString(),
  },
  {
    id: "10",
    source: "MYCA Orchestrator",
    destination: "Redis Cache",
    service: "Redis",
    risk: "Low",
    direction: "both",
    inBytes: "120.5 KB",
    outBytes: "35.2 KB",
    action: "Allow",
    timestamp: new Date().toISOString(),
  },
];

export async function GET() {
  // In production, fetch from Python backend:
  // const response = await fetch('http://localhost:8000/api/flows');
  // const data = await response.json();
  // return NextResponse.json(data);
  
  return NextResponse.json(flows);
}
