-- MycoForge component name reduction
UPDATE components SET name = 'LoRa Antenna 13dBi', description = '915Mhz / 13 dBi gain Yagi LoRa Antenna - Excellent for Helium Hotspot Mining' WHERE id = 'B01FV1DD9C';
UPDATE components SET name = 'LoRa Antenna 10dBi', description = '915MHz Antenna 10dBi Gain for Meshtastic LoRa Long Range Soft Whip Antenna, 17cm' WHERE id = 'B0DB5MH38T';
UPDATE components SET name = 'LoRa Antenna 3dBi', description = '915MHz LoRa Antenna Indoor 3dBi Gain Omni SMA Male + IPEX Cable 2 Pcs' WHERE id = 'B0CTXL61LY';
UPDATE components SET name = 'LoRa Antenna', description = 'RAIGEN LoRa Fiberglass Antenna & Magnetic Base, SMA Male Connector 6.5ft Raigen-' WHERE id = 'B0D5QHXYGF';
UPDATE components SET name = 'SMA to N Cable 15m', description = 'Ultra Flexible SMA to N Cable 15-Meter(49.2 Ft) Low Loss RG58 N Male to SMA Male' WHERE id = 'B01FVWCKKE';
UPDATE components SET name = 'GNSS Antenna', description = 'Waveshare GNSS L1+L5 Dual-Frequency Active Antenna, SMA-J Connector, Supports Mu' WHERE id = 'B0CH88LFS4';
UPDATE components SET name = 'Antenna', description = 'WAVLINK AC1200 Outdoor Long Range Wi-Fi Extender,Dual Band Outdoor Access Point' WHERE id = 'B0DGG7GJL7';
UPDATE components SET name = '4G LTE Antenna', description = 'Wlaniot 4G LTE GSM Antenna Omni-Directional 700-2600MHZ Adhesive Mount Antenna w' WHERE id = 'B07GNC8DHH';
UPDATE components SET name = 'Fanttik E1 Max 3.7V Mini', description = 'Fanttik E1 Max 3.7V Mini Electric Screwdriver, Precision Screwdriver Set, 50-in-' WHERE id = 'B0BGWRWRX2';
UPDATE components SET name = 'KOOTION 256GB Micro SD Card', description = 'KOOTION 256GB Micro SD Card UHS-I U3 V30 4K for Camera/Action Camera/Drone/Smart' WHERE id = 'B0CF5KH6ZM';
UPDATE components SET name = 'MyCobot 280 Camera Flange', description = 'MyCobot 280 Camera Flange Designed from Elephant Robotics' WHERE id = 'B09PH867P6';
UPDATE components SET name = 'SMA to IPX Cable', description = 'TUOLNK 5PCS SMA Female to IPX U.FL RG178 Coaxial Cable, 12 inch(30cm) SMA MHF1 U' WHERE id = 'B098QH631G';
UPDATE components SET name = 'Cat8 RJ45 Connector', description = 'kwmobile Keystone Module Jacks - 24 Piece CAT-8 Shielded Keystone Jack RJ45 Cat' WHERE id = 'B08JPL85H8';
UPDATE components SET name = 'Medium Grey Box', description = 'Medium grey box chassis' WHERE id = 'c1772756532326';
UPDATE components SET name = 'Junction Box', description = 'QILIPSU Junction Box with Mounting Plate 110x80x70mm, Clear Cover Plastic DIY El' WHERE id = 'B07H5C8BB6';
UPDATE components SET name = 'Small Grey Box', description = 'Small grey box chassis' WHERE id = 'c1772756572006';
UPDATE components SET name = 'White Box Chassis', description = 'White box chasis' WHERE id = 'c1772756491478';
UPDATE components SET name = 'ESP32 Dev Board', description = '12 Packs ESP32-DevKitC-32 Development Board modules(ESP-32D,ESP-32 CP2012 USB C' WHERE id = 'B0DT3RTK9D';
UPDATE components SET name = '18650 Shield Board', description = '18650 Battery Shield Board V3 Micro USB Charger ESP32 for Raspberry Pi and Ardui' WHERE id = 'B0CNSSS6T4';
UPDATE components SET name = 'ESP32 Dev Board', description = '2 Pack ESP32 LoRa V3 Development Board + 1100mAh Battery + Protect Case Set - wi' WHERE id = 'B0F1CXG94J';
UPDATE components SET name = 'NEO-6M', description = '2Pack GPS Module,Navigation Satellite Positioning NEO-6M,Arduino GPS, Drone Micr' WHERE id = 'B0B31NRSD2';
UPDATE components SET name = 'ESP32-S3 Dev Kit', description = '3PCS ESP32 ESP32-S3 Development Board Type-C WiFi+Bluetooth Internet of Things D' WHERE id = 'B0C9H7Y66W';
UPDATE components SET name = 'AMD Mini PC Ryzen', description = 'ACEMAGICIAN AMD Mini PC Ryzen 7430U, Mini Gaming PC 32GB DDR4 512GB SSD, Mini Co' WHERE id = 'B0D56GV4X1';
UPDATE components SET name = 'WS2812B', description = 'ALITOVE 100pcs WS2812B Addressable 5050 Smart RGB LED Pixel Light on Black Heat' WHERE id = 'B01D1FFVOA';
UPDATE components SET name = '256GB Micro SD Card', description = 'Amazon Basics Micro SDXC Memory Card with Full Size Adapter, A2, U3, Read Speed' WHERE id = 'B08TJRVWV1';
UPDATE components SET name = 'OV5647', description = 'Arducam for Raspberry Pi Zero Camera Module, 5MP OV5647 1080P Webcam on Raspbian' WHERE id = 'B01LY05LOE';
UPDATE components SET name = 'ESP32 Dev Board', description = 'AYWHP 3 Set ESP32 LoRa Development Board with Case, LoRa V3 Meshtastic ESP32 WiF' WHERE id = 'B0DMN28TRW';
UPDATE components SET name = 'Beelink Mini PC', description = 'Beelink Mini S12 Pro Mini Pc,Intel 12th Gen Alder Lake-N100 (4C/4T, Up to 3.4GHz' WHERE id = 'B0CRNPBGNB';
UPDATE components SET name = 'BME688 Sensor', description = 'BME688 Environmental Sensor with AI Function, Supports Temperature/Humidity/Baro' WHERE id = 'B0BZ4WV4PQ';
UPDATE components SET name = 'SX1278', description = 'Comimark 2Pcs LoRa SX1278 Long Range RF Wireless Power Mental Module SX1276 5Km' WHERE id = 'B07W6ZPH7D';
UPDATE components SET name = 'TTP223', description = 'D-FLIFE 100pcs TTP223 Touch Switch Module Capacitive Sensor Switch DIY for Ardui' WHERE id = 'B0C6XKXPVX';
UPDATE components SET name = 'ESP32 Dev Board', description = 'DIYmall 2pcs 915MHz LoRa32 V3 ESP32 S3 WiFi+BT Development Board with 5DBi LoRa' WHERE id = 'B0CY1XKZQC';
UPDATE components SET name = 'TCRT5000', description = 'DWEII 12PCS Obstacle Avoidance Sensor TCRT5000 5V 1 Way IR Infrared Reflective S' WHERE id = 'B0B53DPBTZ';
UPDATE components SET name = 'Dupont Wire 40pin', description = 'ELEGOO 120pcs Multicolored Dupont Wire 40pin Male to Female, 40pin Male to Male,' WHERE id = 'B01EV70C78';
UPDATE components SET name = 'ESP32 Dev Board', description = 'ELEGOO 3PCS ESP-32 Development Board USB-C, 2.4GHz Dual Mode WiFi+Bluetooth Dual' WHERE id = 'B0D8T53CQ5';
UPDATE components SET name = 'myCobot 280 Robotic Arm', description = 'ELEPHANT ROBOTICS Robotic Arm myCobot 280 Raspberry Pi 4B - Open Source 6DOF Col' WHERE id = 'B0B9W96SD6';
UPDATE components SET name = 'Mini Speaker 8 Ohm', description = 'eMagTech 10pcs Mini Speaker 8 Ohm 1W 20x30mm Magnetic Speakers Replacement Compa' WHERE id = 'B0DLKLY669';
UPDATE components SET name = 'ESP32 Dev Board', description = 'ESP32 Development Board WT32-SC01 Plus with 3.5in 320 * 480 Based on ESP32-WROVE' WHERE id = 'B0BKL93X2J';
UPDATE components SET name = 'ESP32-S3 Dev Board', description = 'ESP32 ESP32-S3 Development Board AYWHP 5 Pcs ESP32 S3 ESP32-S3-DevKitC Module wi' WHERE id = 'B0DG8L5NG5';
UPDATE components SET name = 'Pi Zero Camera 5MP', description = 'for Raspberry Pi Zero Camera Module 160 FOV 5MP Fisheye Lens Camera Wide Angle 1' WHERE id = 'B083XMGSVP';
UPDATE components SET name = 'GC2145', description = 'FORIOT GC2145 Camera 160? I2C Wide-Angle Lens 2 Megapixel Sensor Cam Module DVP' WHERE id = 'B0DRJ5NTV3';
UPDATE components SET name = 'ESP32 Case 5-in-1', description = 'HCJYC 5 in 1 Protective Accessories Soft Silicone Case & EVA Carrying Case & 3 P' WHERE id = 'B0CJ9C4FFH';
UPDATE components SET name = 'HP 15.6 Laptop', description = 'HP 15.6 inch Laptop, HD Touchscreen Display, AMD Ryzen 5 7520U, 8 GB RAM, 512 GB' WHERE id = 'B0DWPKQ3LH';
UPDATE components SET name = 'INA333', description = 'JESSINIE INA333 Amplifier Module 3 Operational Amplifier INA333 Low Power Precis' WHERE id = 'B0BBLSNJCJ';
UPDATE components SET name = 'Jetson Nano', description = 'Jetson Nano B01 4GB SUB Development Kit Official Board for AI and Robotics Yahbo' WHERE id = 'B0BNQDV3FR';
UPDATE components SET name = 'Jetson Orin Nano 8GB', description = 'Jetson Orin Nano 8GB Developer Kit' WHERE id = 'c1772765873359';
UPDATE components SET name = 'LILYGO T-A7670G 4G', description = 'LILYGO T-A7670G R2 4G LTE CAT1 SIM Module ESP32 TTGO Development Board Support G' WHERE id = 'B0CLLNMRX7';
UPDATE components SET name = 'ESP32-S3 Board', description = 'LILYGO T-BeamSUPREME Meshtastic 915Mhz ESP32-S3 LoRa L76K GPS WiFi Bluetooth Mod' WHERE id = 'B0CXJ71NB6';
UPDATE components SET name = 'ESP32-S3 Board', description = 'LILYGO T-Deck Plus ESP32-S3 915Mhz LORA-89 SX1262 Ulbox GPS 2.8-inch Display TTG' WHERE id = 'B0FBGTYQH3';
UPDATE components SET name = 'SX1262', description = 'LILYGO T-Echo Meshtastic LoRa SX1262 Wireless Module 915MHz TTGO Development Boa' WHERE id = 'B0B658DZ9Z';
UPDATE components SET name = 'LILYGO T-SIM7000G', description = 'LILYGO T-SIM7000G ESP32-WROVER-B Solar Charge SIM GPS Antenna CH9102F 16MB 2G/NB' WHERE id = 'B099RQ7BSR';
UPDATE components SET name = 'LoRa Antenna 915MHz', description = 'Long Range Soft Whip 915MHz LoRa Antenna with SMA Male Connector for Heltec V3 M' WHERE id = 'B0DKSS4K6N';
UPDATE components SET name = 'GPS Galileo Tracker', description = 'MakerFocus Wireless Tracker Supports GPS Galileo Multi-System Joint Positioning' WHERE id = 'B0DGGFFY8K';
UPDATE components SET name = 'GPS Galileo Tracker', description = 'MakerFocus Wireless Tracker Supports GPS Galileo Multi-System Joint Positioning' WHERE id = 'B0CQT9J4K8';
UPDATE components SET name = 'Li-Po 10000mAh', description = 'MakerHawk 3.7V 10000mAh LiPo Battery Rechargeable 1S 3C Lithium Polymer Battery' WHERE id = 'B0DP634VQ5';
UPDATE components SET name = 'Li-Po 6600mAh', description = 'MakerHawk 3.7V 6000mAh LiPo Battery Rechargeable 1S 3C Lithium Polymer Battery w' WHERE id = 'B0D3LP1G3F';
UPDATE components SET name = 'LoRa Antenna Magnetic', description = 'Meshtastic Long Range 915MHz Lora Magnetic Base Antenna with SMA Male for ESP32' WHERE id = 'B0DMK4QPPD';
UPDATE components SET name = 'MSI Gaming RTX 5090 32G', description = 'MSI Gaming RTX 5090 32G SUPRIM Liquid SOC Graphics Card (32GB GDDR7, 512-bit, Ex' WHERE id = 'B0DT7K9VV3';
UPDATE components SET name = 'MyoWare 2.0', description = 'MyoWare 2.0 Muscle Sensor-Compatible with Arduino- All-in-one electromyography (' WHERE id = 'B0BM2YKHRR';
UPDATE components SET name = 'ESP32 Board', description = 'MyoWare 2.0 Wireless Shield - wirelessly Transmit Data with The ESP32-WROOM chip' WHERE id = 'B0CZPN3D9K';
UPDATE components SET name = 'NZXT Kraken 360 AIO', description = 'NZXT Kraken 360 RGB - 360mm AIO CPU Liquid Cooler - RL-KR360-W1 - Customizable 1' WHERE id = 'B0BY3GTG48';
UPDATE components SET name = 'OV2640 ESP32-CAM', description = 'OV2640 Camera Esp32 Cam Camera Module,Aideepen OV2640 Camera 160? Wide-Angle Len' WHERE id = 'B0DNZ3ZD36';
UPDATE components SET name = 'T-SIM7000G ESP32', description = 'TTGO T-SIM7000G Module ESP32-WROVER-B Chip WiFi Bluetooth 18560 Battery Holder S' WHERE id = 'B0CJM767KB';
UPDATE components SET name = 'E-Ink E290 Dev Board', description = 'Vision Master E290 Development Board with 2.9" E-Ink Display Screen, SX1262 Chip' WHERE id = 'B0D9JWT4P1';
UPDATE components SET name = '5" Round LCD 1080p', description = 'waveshare 5inch Round LCD 1080 x 1080, IPS 10-Point Touch Screen for Raspberry P' WHERE id = 'B0CNH8H6NG';
UPDATE components SET name = 'Jetson Nano', description = 'Waveshare Jetson Nano Development/Expansion Kit, 16GB eMMC, Alternative Solution' WHERE id = 'B09TXL8NQ5';
UPDATE components SET name = 'SIM7600G-H', description = 'Waveshare SIM7600G-H 4G Communication Module, Compatible with Raspberry Pi 5/4B/' WHERE id = 'B0BTP93H8H';
UPDATE components SET name = 'Jetson Orin NX', description = 'Yahboom Jetson Orin NX Super 157TOPS with AI Voice Module,IMX219 CSI Camera,256G' WHERE id = 'B0FQ5XWXMG';
UPDATE components SET name = 'TF-Luna', description = 'youyeetoo TF-Luna Lidar Sensor Kit, with 1x USB-TTL Adapter 1x Dupont Line, 0.2-' WHERE id = 'B088BBJ9SQ';
UPDATE components SET name = 'Soil Moisture Meter', description = '4-in-1 Soil Moisture Meter Digital Plant Temperature/Soil Moisture/PH Meter/Sunl' WHERE id = 'B0DF4TB93J';
UPDATE components SET name = 'Heat Shrink Tubing', description = '560PCS Heat Shrink Tubing 2:1, Eventronic Electrical Wire Cable Wrap Assortment' WHERE id = 'B072PCQ2LW';
UPDATE components SET name = '8 Port 10G Switch', description = '8 Port 10G Ethernet Switch Unmanaged,with 8X 10Gb Base-T Ports, NICGIGA 10Gbps N' WHERE id = 'B0CQXMPXKC';
UPDATE components SET name = 'Bare Copper Wire 20ga', description = '99.9% Solid Bare Copper Wire, 20 Gauge 310Ft,1lb Spool,Supplied by Wonderway (20' WHERE id = 'B0CGR8ZLTZ';
UPDATE components SET name = 'Centrifuge Tubes 15mL', description = 'Ackers Conical Centrifuge Tubes 15mL, 100 Pcs Sterile Plastic Test Tubes with Sc' WHERE id = 'B08FM9334M';
UPDATE components SET name = 'Anker TB4 Cable 3.3ft', description = 'Anker Prime Thunderbolt 4 Cable, 3.3 ft USB C to USB C Cable, 240W Charging, 40G' WHERE id = 'B0DDQDG6GF';
UPDATE components SET name = 'Anker TB4 Cable', description = 'Anker Thunderbolt 4 Certified USB C to USB C Cable, 8K/4K Display/40Gbps Compati' WHERE id = 'B0CDH4FGZY';
UPDATE components SET name = 'Anker USB-C Hub', description = 'Anker USB-C Hub, USBC to 4-Port USBC Adapter, Multiport USB C Splitter, USB 3.2' WHERE id = 'B0CS69N2Z6';
UPDATE components SET name = 'Digital Calendar', description = 'ApoloSign Digital Calendar: Electronic Calendar, Smart Touchscreen Interactive D' WHERE id = 'B0DJ7GNDL8';
UPDATE components SET name = 'Storage Cabinet 16 Drawer', description = 'Arteza 16 Drawer Storage Cabinet, 17.7 x 8.2 x 10.9 inches, White, Plastic Drawe' WHERE id = 'B08VNB7MVQ';
UPDATE components SET name = 'Wire Spool Rack', description = 'BISupply Wall Mount Electrical Wire Spool Rack Holder - 2 Rod Cable Rack for Rib' WHERE id = 'B0BM26L46T';
UPDATE components SET name = 'BNUOK 120pcs M3 x 50mm', description = 'BNUOK 120pcs M3 x 50mm Hex Socket Head Cap Screws Bolts, 12.9 Grade Alloy Steel,' WHERE id = 'B0DJQGS5JL';
UPDATE components SET name = 'Cable', description = 'Cable Matters 8K DisplayPort 1.4 to HDMI 2.1 Adapter with 4K 240Hz / 8K 60Hz, Un' WHERE id = 'B08XFSLWQF';
UPDATE components SET name = 'Cat8 Ethernet Cable', description = 'Cable Matters All-In-One Modular Ethernet Crimping Tool Cat 8 (Cat5 Cat6 Cat7 Ca' WHERE id = 'B0CH3TDJ4B';
UPDATE components SET name = 'CalDigit TS4 Thunderbolt 4 Dock', description = 'CalDigit TS4 Thunderbolt 4 Dock - 18 Ports, 98W Charging, 40Gb/s Thunderbolt 4,' WHERE id = 'B09GK8LBWS';
UPDATE components SET name = 'Chanzon SMD Fast Switching/Schottky/Rectifier Diode', description = 'Chanzon SMD Fast Switching/Schottky/Rectifier Diode Assorted Kit (15 Values Tota' WHERE id = 'B07BTXK1NG';
UPDATE components SET name = 'PLA Filament 1.75mm Black', description = 'Creality 2kg Black & White PLA 1.75mm Filament Bundle for 3D Printing with No-Ta' WHERE id = 'B0C4TNQZYY';
UPDATE components SET name = 'PLA Filament 1.75mm', description = 'Creality 3D Printer Filament 1.75mm 4KG, PLA Filament Bulk +/- 0.02mm, 4 Pack 1k' WHERE id = 'B0DFGB288Y';
UPDATE components SET name = 'ABS Filament 1.75mm Black', description = 'Creality ABS Filament 1.75mm Black 3D Printer Filaments, 1kg(2.2lbs) Neatly-Woun' WHERE id = 'B0F9NXB9DB';
UPDATE components SET name = 'ABS Filament 1.75mm White', description = 'Creality ABS Filament 1.75mm White 3D Printer Filaments, 1kg(2.2lbs) Neatly-Woun' WHERE id = 'B0F9NZDP3P';
UPDATE components SET name = 'Filament', description = 'Creality CFS Multi Color Auto Filament System Anti-Moisture Filament Storage Aut' WHERE id = 'B0F4KG3WWK';
UPDATE components SET name = 'PLA Filament 1.75mm', description = 'Creality Hyper PLA Filament 1.75mm, RFID 3D Printer Filament for High Speed 30-6' WHERE id = 'B0DMVG2TFL';
UPDATE components SET name = 'Creality K2 Plus Build Plate', description = 'Creality K2 Plus Build Plate Epoxy Resin Coating 370x370mm Spring Steel Magnetic' WHERE id = 'B0DP2S8V6N';
UPDATE components SET name = 'PETG Filament 1.75mm', description = 'Creality PETG Filament 1.75, 3D Printer Filament, Excellent Toughness High Preci' WHERE id = 'B0BZCX99NV';
UPDATE components SET name = 'DEPEPE 500ml Plastic Safety Wash', description = 'DEPEPE 6pcs 500ml Plastic Safety Wash Bottles Lab Squeeze Bottle LDPE Squirt Bot' WHERE id = 'B07DB1HCKP';
UPDATE components SET name = 'EISCO CH0688 Labs Clamp Retort,', description = 'EISCO CH0688 Labs Clamp Retort, 3 PVC Coated Prongs (Opens to 90mm in Dia.) with' WHERE id = 'B00AWS3QV0';
UPDATE components SET name = 'PLA Filament 1.75mm Black', description = 'ELEGOO PLA Plus Filament 1.75mm Black & White 4KG, PLA+ Tougher and Stronger 3D' WHERE id = 'B0CHS79BGL';
UPDATE components SET name = 'ELEGRP USB Charger Wall Outlet,', description = 'ELEGRP USB Charger Wall Outlet, 15 Amp Duplex Tamper Resistant Receptacle Plug w' WHERE id = 'B09GLSWMQM';
UPDATE components SET name = 'ELEGRP USB Outlets, 15 Amp', description = 'ELEGRP USB Outlets, 15 Amp Wall Outlet with 3 USB Ports, Dual USB C Ports Outlet' WHERE id = 'B0CTZF7MNP';
UPDATE components SET name = 'ELEGRP USB Outlets, 15 Amp', description = 'ELEGRP USB Outlets, 15 Amp Wall Outlet with 3 USB Ports, Dual USB C Ports Outlet' WHERE id = 'B0CTZQYNKY';
UPDATE components SET name = 'ELEPHANT ROBOTICS Robot Arm Accessory,', description = 'ELEPHANT ROBOTICS Robot Arm Accessory, Suction Pump for MyCobot & MechArm' WHERE id = 'B09PH8YCVM';
UPDATE components SET name = 'ES EVVIVA SCIENCES Pre-Poured Black', description = 'ES EVVIVA SCIENCES Pre-Poured Black Malt Extract Agar Plates - Includes Both Bla' WHERE id = 'B099P57WJN';
UPDATE components SET name = 'PLA Filament 1.75mm', description = 'eSUN PLA+ Filament 1.75mm, 3D Printer Filament PLA Plus, Dimensional Accuracy +/' WHERE id = 'B0BN4W6P6Q';
UPDATE components SET name = 'ESYTEOOT Bamboo Screwdriver Organizer Rack', description = 'ESYTEOOT Bamboo Screwdriver Organizer Rack Desktop Hand Tool Stand and Repair To' WHERE id = 'B0CGG19X3L';
UPDATE components SET name = 'exgoofit Phono RCA Screws Male', description = 'exgoofit Phono RCA Screws Male Female Plug to AV Screw Terminal Audio/Video Conn' WHERE id = 'B078HY1WP1';
UPDATE components SET name = 'EZ BioResearch Potato Dextrose Agar', description = 'EZ BioResearch Potato Dextrose Agar (PDA) Plates for Mushroom Cultivation (10 Pr' WHERE id = 'B074GG4L95';
UPDATE components SET name = 'Flexi Rods Garage Organizer Wall', description = 'Flexi Rods Garage Organizer Wall Hanger - Garden Tool Rack for Grass Trimmer, He' WHERE id = 'B0BPRZ82GD';
UPDATE components SET name = 'Furrion Enhanced Multi-Zone Wall Thermostat', description = 'Furrion Enhanced Multi-Zone Wall Thermostat with App Control for Chill RV Air Co' WHERE id = 'B0C9JSY1KM';
UPDATE components SET name = 'haisstronica Wire Stripper Crimping Tool,AWG', description = 'haisstronica Wire Stripper and Crimping Tool,AWG 24-10 Automatic Stripper Tool w' WHERE id = 'B0C3GRTT2G';
UPDATE components SET name = 'Hilitchi 60-Pcs 100 to 500K', description = 'Hilitchi 60-Pcs 100 to 500K ohm 3296W Multiturn Trimmer Potentiometer Assortment' WHERE id = 'B0711MB4TL';
UPDATE components SET name = 'Hot Air Rework Station, Prostormer', description = 'Hot Air Rework Station, Prostormer 120V Digital Display Heat Gun with 3 Sets Sto' WHERE id = 'B08VNYPL7H';
UPDATE components SET name = 'Hotop Inoculation Loop Mycology Reusable', description = 'Hotop 2 Pcs Inoculation Loop Mycology Reusable Inoculating Loop with 90 Replacea' WHERE id = 'B087QGTZ1G';
UPDATE components SET name = 'iRobot Authentic Parts Cleaning Solution,', description = 'iRobot Authentic Replacement Parts Cleaning Solution, 6-Pack' WHERE id = 'B09KYKLGKP';
UPDATE components SET name = 'JROUTH 1500pcs Screws Assortment ,', description = 'JROUTH 1500pcs Screws Assortment , M2 M3 M4 M5 10.9 Grade Alloy Steel Hex Flat H' WHERE id = 'B0B6PVJTHY';
UPDATE components SET name = 'Kashi Scientific 2mL Microcentrifuge Tube', description = 'Kashi Scientific 2mL Microcentrifuge Tube with Safe Lock Snap Cap [500/Pack] 2 m' WHERE id = 'B0C3571PLB';
UPDATE components SET name = 'KOOTION 32GB Micro SD Cards', description = 'KOOTION 32GB Micro SD Cards 10-Pack, UHS-1 TF Flash Memory Card, U1, Class 10 mi' WHERE id = 'B0D63D9Z5F';
UPDATE components SET name = 'Large Junction Box', description = 'Large Waterproof Electrical Junction Box, IP67 Waterproof Clear ABS Plastic Encl' WHERE id = 'B0DXT464VB';
UPDATE components SET name = 'Letool 30 Pairs JST 1.25mm', description = 'Letool 30 Pairs JST 1.25mm 2 Pin Micro Male Female Connector Plug with Red Black' WHERE id = 'B013JRWCBU';
UPDATE components SET name = 'INA128', description = 'Linear Instrumentation Amplifier 10PCS INA128UA INA128 INA128U SOP-8 New for Arr' WHERE id = 'B0DPFX4PDP';
UPDATE components SET name = 'M4-0.7 x 20mm Flat Head', description = 'M4-0.7 x 20mm Flat Head Socket Cap Screws Bolts, Stainless Steel 18-8 (304), Bri' WHERE id = 'B0949JNZWQ';
UPDATE components SET name = 'M4-0.7 x 25mm Flat Head', description = 'M4-0.7 x 25mm Flat Head Socket Cap Screws Bolts, Stainless Steel 18-8 (304), Bri' WHERE id = 'B0949M4PMD';
UPDATE components SET name = 'M4-0.7 x 8mm Flat Head', description = 'M4-0.7 x 8mm Flat Head Socket Cap Screws Bolts, Stainless Steel 18-8 (304), Brig' WHERE id = 'B0949KFZ8V';
UPDATE components SET name = 'METALTER Screwdriver Rack, Small Tool', description = 'METALTER Screwdriver Rack, Small Tool Storage Holder for Desk Top, Work bench Or' WHERE id = 'B0B75JJQ9Q';
UPDATE components SET name = 'Mushroom 1 Big Body', description = 'Mushroom One Big Body' WHERE id = 'c1772756665580';
UPDATE components SET name = 'MyMed of 40 Sterile Petri', description = 'MyMed Pack of 40 Sterile Petri Dishes with Lids (90 x 15 mm), 2ml Plastic Pipett' WHERE id = 'B09VKF38KW';
UPDATE components SET name = 'New Age America? 93pcs Rubber', description = 'New Age America? 93pcs Rubber Grommets Kit' WHERE id = 'B0D19C25NS';
UPDATE components SET name = 'Official Creality K1 Max Glossy', description = 'Official Creality K1 Max Glossy PEO and Matte PEI Double Side Build Plate Kit, 3' WHERE id = 'B0CZ79Q7XM';
UPDATE components SET name = 'OREI SplitExtend HDMI Splitter Extended', description = 'OREI SplitExtend HDMI Splitter Extended Display for Dual Monitor - Multi-Monitor' WHERE id = 'B0C3PFQZ4G';
UPDATE components SET name = 'Outdoor Electrical Box Thermostat Fan,', description = 'Outdoor Electrical Box with Thermostat and Fan, Cold-Rolled Steel Plate, Aluminu' WHERE id = 'B0CY2BPPD4';
UPDATE components SET name = 'ASA Filament 1.75mm', description = 'OVERTURE ASA Filament 1.75mm, 1kg Spool (2.2lbs) 3D Printer Filament, Premium An' WHERE id = 'B09DCQ972K';
UPDATE components SET name = 'ASA Filament 1.75mm', description = 'OVERTURE ASA Filament 1.75mm, 1kg Spool (2.2lbs) 3D Printer Filament, Premium An' WHERE id = 'B0BN8SSDPL';
UPDATE components SET name = 'ASA Filament 1.75mm', description = 'OVERTURE ASA Filament 1.75mm, 1kg Spool (2.2lbs) 3D Printer Filament, Premium An' WHERE id = 'B08PF938JJ';
UPDATE components SET name = 'Cable', description = 'Qrity 20 PCS Rubber Grommets Cable Railing, Car Grommet, Cable Railing Protectiv' WHERE id = 'B0CQXDXRZ2';
UPDATE components SET name = 'Quoya Smart Curtain Tracks- Belt', description = 'Quoya Smart Curtain Tracks- Replacement Belt (14.4 Meters)' WHERE id = 'B086Z6XMWP';
UPDATE components SET name = 'Replace DYMO LetraTag Label Maker', description = 'Replace for DYMO LetraTag Label Maker Refill 91331 White Plastic Tape 12mm x 4m' WHERE id = 'B074JZ6NWV';
UPDATE components SET name = 'risingsaplings 500pcs 1206 SMD resistors', description = 'risingsaplings 500pcs 1206 SMD resistors kit 270R 1K 4K7 10K 20K (5 Types Each 1' WHERE id = 'B0CJ78KXRH';
UPDATE components SET name = 'ruthex Threaded Inserts M2 +', description = 'ruthex Threaded Inserts M2 + M3 + M4 + M5 Assortment Box - 70 + 100 + 50 + 50 Pi' WHERE id = 'B08K1BVGN9';
UPDATE components SET name = 'SenseCAP Card Tracker T1000-E', description = 'SenseCAP Card Tracker T1000-E for Meshtastic' WHERE id = 'B0DJ6KGXKB';
UPDATE components SET name = 'Sharpie Permanent Markers Bulk Set', description = 'Sharpie Permanent Markers Bulk Set Fine Tip Markers Set For Plastic Metal Wood A' WHERE id = 'B00G4CJ8GK';
UPDATE components SET name = 'Small Junction Box', description = 'Small Waterproof Electrical Junction Box?IP67 Waterproof Clear ABS Plastic Enclo' WHERE id = 'B0DXT4WTR4';
UPDATE components SET name = 'PLA Filament 1.75mm', description = 'SUNLU 3D Printer Filament PLA Filament 1.75mm, Neatly Wound 3D Printing Filament' WHERE id = 'B07ZNG4L9P';
UPDATE components SET name = 'AD620', description = 'Teyleten Robot Millivolt/Microvolt Voltage Amplifier Module AD620 Instrumentatio' WHERE id = 'B08QM9SM1W';
UPDATE components SET name = 'THANDBLE DisplayPort to HDMI Splitter', description = 'THANDBLE DisplayPort to HDMI Splitter for Multi Monitor Adapter, HDMI Splitter E' WHERE id = 'B0DDL48VFX';
UPDATE components SET name = 'THANDBLE USB C to 3', description = 'THANDBLE USB C to 3 HDMI Adapter with 100W PD Charging, Triple 4K60Hz Monitor Ex' WHERE id = 'B0DK3G77TC';
UPDATE components SET name = 'Thermaltronics TMT-TC-2 Tip Tinner in', description = 'Thermaltronics TMT-TC-2 Tip Tinner (20g) in 0.8oz Container' WHERE id = 'B00NS4J6BY';
UPDATE components SET name = 'Junction Box', description = 'TICONN Waterproof Electrical Junction Box IP67 ABS Plastic Enclosure with Hinged' WHERE id = 'B0B87TNPRY';
UPDATE components SET name = 'Junction Box', description = 'TICONN Waterproof Electrical Junction Box IP67 ABS Plastic Enclosure with Hinged' WHERE id = 'B0B87V7QTH';
UPDATE components SET name = 'Twippo Heat Shrink Tubing Kit', description = 'Twippo Heat Shrink Tubing Kit 355pcs - 3:1 Dual Wall Adhesive Lined - Electrical' WHERE id = 'B0D2PRQKWL';
UPDATE components SET name = 'Tyimble 2024 Electric Drill Plate', description = 'Tyimble 2024 Electric Drill Plate Cutter - Efficient Metal Shears Attachment for' WHERE id = 'B0CN1N7WRZ';
UPDATE components SET name = 'USB C to USB C', description = 'USB C to USB C Hub Dual Monitor Adapter with 4K@60Hz USB4 Display Ports Video Ou' WHERE id = 'B0DPWZ6W5L';
UPDATE components SET name = 'uxcell Knurled Insert Nuts, 50pcs', description = 'uxcell Knurled Insert Nuts, 50pcs M4 x 4mm L x 6mm OD 3D Printing Brass Nuts Fem' WHERE id = 'B0CTCSJ7Y8';
UPDATE components SET name = 'uxcell M3x100mm Pushrod Connector Stainless', description = 'uxcell M3x100mm Pushrod Connector Stainless Steel Rod Linkage,for RC Boat,Car,Ai' WHERE id = 'B07MSC2YGT';
UPDATE components SET name = 'VEVOR Wall Mounted Storage Rack', description = 'VEVOR Wall Mounted Storage Rack System, 30-Bin Parts Rack Organizer with Wall Pa' WHERE id = 'B0CY54RM4K';
UPDATE components SET name = 'VIVO Large Keyboard Tray Under', description = 'VIVO Large Keyboard Tray Under Desk Pull Out Platform with Pencil Drawer, Extra' WHERE id = 'B0B9V8Z3CT';
UPDATE components SET name = 'Junction Box', description = 'Waterproof Electrical Junction Box?IP67 Waterproof Clear ABS Plastic Enclosure B' WHERE id = 'B0DXTFT6WM';
UPDATE components SET name = 'Junction Box', description = 'YETLEBOX Outdoor Waterproof Electrical Box Junction Box Weatherproof IP67 ABS Pl' WHERE id = 'B0BZHGCBTH';
UPDATE components SET name = 'Yopay Media Storage Bottles GL45', description = 'Yopay 10 Pack Media Storage Bottles with GL45 Blue Screw Cap, 250ml Reusable Gla' WHERE id = 'B0BVFMR1VY';
UPDATE components SET name = 'Cable', description = 'ZIKNYDO 16K for Thunderbolt 5 Cable 6.6FT/2m, USB C 80Gbps Data Transfer, 120Gbp' WHERE id = 'B0FCMSRJ2J';
UPDATE components SET name = '19V Power Cord Samsung TV', description = '19V Power Cord for Samsung TV 32" UN32 J4000 J4500 J5205 J5003 J525D UN32J4000AF' WHERE id = 'B0B1LM2V5W';
UPDATE components SET name = '200mm Width PVC Heat Shrink', description = '200mm(7.9in) Width PVC Heat Shrink Wrap Tube 18650 21700 26650 Lithium Battery D' WHERE id = 'B09SVFL33L';
UPDATE components SET name = '1?8?6?5?0 Batter?y 9900m?A?h W?i?th 18650', description = '4 Pack 1?8?6?5?0 Rechargeable Batter?y 9900m?A?h W?i?th 18650 Battery Charger,Un' WHERE id = 'B0CN63ZQ2J';
UPDATE components SET name = 'Li-Po 3700mAh', description = '4X EEMB 3.7V Lipo Battery 3700mAh 103395 Rechargeable Lithium Polymer ion Batter' WHERE id = 'B08HGSXYM1';
UPDATE components SET name = 'Li-Po', description = 'ACEIRMC 3pcs CN3065 Mini Solar Lipo Charger Board Lithium Battery Charge Chip Mi' WHERE id = 'B0B58S6L6W';
UPDATE components SET name = 'Cat8 Cable', description = 'Cable Matters 20-Pack 23-24AWG Shielded Cat8 RJ45 Pass Through Connector with Lo' WHERE id = 'B0C2WS46WM';
UPDATE components SET name = 'Cat8 Ethernet Cable', description = 'Cat8 Flat Ethernet Cable 100 FT Indoor & Outdoor, Invisable Ultra-Thin Ethernet' WHERE id = 'B0DHXTFS5P';
UPDATE components SET name = 'Cat8 Ethernet Cable', description = 'Cat8 Flat Ethernet Cable 50 FT Indoor & Outdoor, Invisable Ultra-Thin Ethernet C' WHERE id = 'B0DHXS26XL';
UPDATE components SET name = 'Cat8 Ethernet Cable', description = 'Cat8 Flat Ethernet Cable 75 FT Indoor & Outdoor, Invisable Ultra-Thin Ethernet C' WHERE id = 'B0DHXQ92RL';
UPDATE components SET name = 'CHANZON 30 Pairs Jst PH', description = 'CHANZON 30 Pairs Jst PH 2.0 mm Pitch 22AWG 2Pin Plug Connector for 10cm and 15cm' WHERE id = 'B0B2D89WLT';
UPDATE components SET name = 'CPZZ 20Pack 18650 Battery Flat', description = 'CPZZ 20Pack 18650 Rechargeable Battery Flat top 3.7v 18650 Rechargeable Battery' WHERE id = 'B0D8PZ8MNL';
UPDATE components SET name = 'TP4056 Charger', description = 'EC Buying 10Pcs TP4056 1A Lithium Battery Charging Board Module USB Type-c 5V 1A' WHERE id = 'B0CRKHTG89';
UPDATE components SET name = 'Elite Cat8 Shielded Riser ,', description = 'Elite Cat8 Shielded Riser (CMR), 40Gb, 2000MHz, S/FTP 22AWG, Solid Pure Copper,' WHERE id = 'B07ZQPFGHX';
UPDATE components SET name = 'TP4057 Charger', description = 'HiLetgo 5pcs TP4057 1A 3.7V Lithium Battery Charging Board with Protection Type-' WHERE id = 'B0CDWZ9MDC';
UPDATE components SET name = 'Cat8 RJ45 Connector', description = 'Itvexeme RJ45 Connectors Tool Free Cat8, Cat8 Field Termination Plug Shielded Mo' WHERE id = 'B0DQ9ZDXDG';
UPDATE components SET name = 'Li-Po 1000mAh', description = 'MakerHawk 3.7V Lipo Battery 1000mAh 803040 Rechargeable Battery Lithium Polymer' WHERE id = 'B0DPZW6KXT';
UPDATE components SET name = 'NAOEVO 22 Gauge Wire 360ft,', description = 'NAOEVO 22 Gauge Wire 360ft, 22 AWG Wire 6 Colors 60ft Each Spool, Flexible Silic' WHERE id = 'B0CMLGS4YG';
UPDATE components SET name = 'Cat8 Ethernet Cable', description = 'Rapink Patch Cables Cat8 1ft 24 Pack Slim, Cat8 Ethernet Patch Cable 40G Support' WHERE id = 'B0CKJ5YPZ5';
UPDATE components SET name = 'Solar Controller', description = 'Solar controller' WHERE id = 'c1772756414292';
UPDATE components SET name = 'Spec5 Relay Solar-Powered Meshtastic LoRa', description = 'Spec5 Relay Solar-Powered Meshtastic LoRa Relay System Long-Range, Communication' WHERE id = 'B0DNF89PF2';
UPDATE components SET name = 'Cat8 Ethernet Cable', description = 'UGREEN Cat 8 Ethernet Cable 6FT, High Speed Braided 40Gbps 2000Mhz Network Cord' WHERE id = 'B0875VL1CJ';
UPDATE components SET name = 'AS3935', description = 'Sensor, AS3935 Storm Distances Detection Sensor SPI I2C Interfacing 2.4V-5.5V fo' WHERE id = 'B07SST5GDB';
UPDATE components SET name = 'Sensor', description = 'Superior Pump 91250 1800GPH Thermoplastic Submersible Utility Pump with 10-Foot' WHERE id = 'B000X05G1A';
-- 180 rows
