#!/usr/bin/env python3
"""
Configure MAS orchestrator with Mycorrhizae API key and fix restart issues.
"""

import paramiko

VM_USER = "mycosoft"
VM_PASS = "REDACTED_VM_SSH_PASSWORD"
VM_188 = "192.168.0.188"

# Generated API key for MAS
MAS_KEY = "myco_mas_kck8lD0E8sPvfob_EQS4xnuuj5h1WB7Ss72Y8xoz9QQ"

def ssh_exec(host, cmd, timeout=60):
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh.connect(host, username=VM_USER, password=VM_PASS, timeout=30)
    stdin, stdout, stderr = ssh.exec_command(cmd, timeout=timeout)
    out = stdout.read().decode('utf-8', errors='replace')
    err = stderr.read().decode('utf-8', errors='replace')
    code = stdout.channel.recv_exit_status()
    ssh.close()
    return out, err, code

def sftp_upload(host, content, remote_path):
    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh.connect(host, username=VM_USER, password=VM_PASS, timeout=30)
    sftp = ssh.open_sftp()
    with sftp.file(remote_path, 'w') as f:
        f.write(content)
    sftp.close()
    ssh.close()

print("=== Investigating MAS Restart Issue ===")

# Check MAS container logs
out, err, _ = ssh_exec(VM_188, "docker logs myca-orchestrator-new --tail 100 2>&1")
print("Last 100 lines of MAS logs:")
print(out[-3000:] if len(out) > 3000 else out)

# Check what environment the MAS container is using
print("\n=== MAS Container Environment ===")
out, err, _ = ssh_exec(VM_188, "docker inspect myca-orchestrator-new --format '{{range .Config.Env}}{{println .}}{{end}}' 2>/dev/null | head -30")
print(out)

# Check MAS directory structure
print("\n=== MAS Directory Structure ===")
out, err, _ = ssh_exec(VM_188, "ls -la ~/mycosoft/mas/ 2>/dev/null || ls -la ~/mas/ 2>/dev/null || echo 'No mas directory found'")
print(out)

# Check if there's an env file for MAS
print("\n=== Looking for MAS env files ===")
out, err, _ = ssh_exec(VM_188, "cat ~/mycosoft/mas/.env 2>/dev/null || cat ~/mas/.env 2>/dev/null || echo 'No .env file'")
print(out)

print("\n=== Creating Mycorrhizae config for MAS ===")
# Create a file that can be sourced by MAS
mycorrhizae_env = f"""# Mycorrhizae Integration for MAS
# Generated by configure_mas_mycorrhizae.py

MYCORRHIZAE_API_URL=http://127.0.0.1:8002
MYCORRHIZAE_API_KEY={MAS_KEY}
"""

# Try to find where MAS reads its config
out, err, _ = ssh_exec(VM_188, "docker inspect myca-orchestrator-new --format '{{.Config.WorkingDir}}'")
print(f"MAS working dir: {out.strip()}")

# Create config file
sftp_upload(VM_188, mycorrhizae_env, "/home/mycosoft/mycorrhizae.env")
print("Created /home/mycosoft/mycorrhizae.env")

# Check how the MAS container was started
print("\n=== MAS Container Start Command ===")
out, err, _ = ssh_exec(VM_188, "docker inspect myca-orchestrator-new --format '{{json .Config.Cmd}}'")
print(f"Command: {out}")

out, err, _ = ssh_exec(VM_188, "docker inspect myca-orchestrator-new --format '{{json .HostConfig.RestartPolicy}}'")
print(f"Restart policy: {out}")

# Try to restart MAS with the new env
print("\n=== Attempting to update MAS container with new env ===")

# Stop the failing container
out, err, _ = ssh_exec(VM_188, "docker stop myca-orchestrator-new 2>&1")
print(f"Stopped: {out}")

# Check the image
out, err, _ = ssh_exec(VM_188, "docker inspect myca-orchestrator-new --format '{{.Config.Image}}'")
image = out.strip()
print(f"Image: {image}")

# Remove old container and recreate with new env
print("\nRecreating MAS container with Mycorrhizae env...")
out, err, code = ssh_exec(VM_188, f"""
docker rm myca-orchestrator-new 2>/dev/null
docker run -d --name myca-orchestrator-new \\
  --restart unless-stopped \\
  -p 8001:8000 \\
  -e MYCORRHIZAE_API_URL=http://127.0.0.1:8002 \\
  -e MYCORRHIZAE_API_KEY={MAS_KEY} \\
  --network host \\
  {image}
""", timeout=60)
print(out)
if err:
    print(f"Error: {err}")

# Wait and check status
import time
time.sleep(10)

print("\n=== Checking MAS Status ===")
out, err, _ = ssh_exec(VM_188, "docker ps --filter name=myca-orchestrator-new --format 'table {{.Status}}'")
print(out)

out, err, _ = ssh_exec(VM_188, "curl -fsS http://127.0.0.1:8001/health 2>&1 || echo 'MAS_HEALTH_FAILED'")
print(f"Health: {out}")

# Show latest logs
print("\n=== Latest MAS Logs ===")
out, err, _ = ssh_exec(VM_188, "docker logs myca-orchestrator-new --tail 30 2>&1")
print(out[-2000:] if len(out) > 2000 else out)
