# Install MycoBrain Service Auto-Start Task
# This script creates a Windows Task Scheduler entry that starts MycoBrain service on boot
# RUN THIS SCRIPT AS ADMINISTRATOR

param(
    [switch]$Remove,
    [switch]$Test
)

$ErrorActionPreference = "Stop"

$MASDir = "C:\Users\admin2\Desktop\MYCOSOFT\CODE\MAS\mycosoft-mas"
$TaskName = "MycoBrain-Service-AutoStart"
$ServiceScript = "$MASDir\services\mycobrain\mycobrain_service_standalone.py"
$LogDir = "$MASDir\logs"
$LogFile = "$LogDir\mycobrain-service.log"

# Check if running as admin
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Host "ERROR: This script must be run as Administrator" -ForegroundColor Red
    Write-Host "Right-click PowerShell and select 'Run as Administrator'" -ForegroundColor Yellow
    exit 1
}

# Check if service script exists
if (-not (Test-Path $ServiceScript)) {
    Write-Host "ERROR: MycoBrain service script not found: $ServiceScript" -ForegroundColor Red
    exit 1
}

if ($Remove) {
    Write-Host "Removing Windows Task Scheduler entry..." -ForegroundColor Yellow
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue
    Write-Host "Task removed!" -ForegroundColor Green
    exit 0
}

if ($Test) {
    Write-Host "Testing MycoBrain service startup..." -ForegroundColor Cyan
    Set-Location $MASDir
    python $ServiceScript
    exit 0
}

Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  Installing MycoBrain Auto-Start Task" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host ""

# Ensure log directory exists
if (-not (Test-Path $LogDir)) {
    New-Item -ItemType Directory -Path $LogDir -Force | Out-Null
    Write-Host "Created log directory: $LogDir" -ForegroundColor Gray
}

# Remove existing task if it exists
Write-Host "Removing any existing task..." -ForegroundColor Gray
Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false -ErrorAction SilentlyContinue

# Create PowerShell wrapper script that starts MycoBrain service
$WrapperScript = "$MASDir\scripts\start-mycobrain-wrapper.ps1"
$WrapperContent = @"
# MycoBrain Service Wrapper
# Auto-generated by install-mycobrain-autostart.ps1

`$ErrorActionPreference = "Continue"
`$MASDir = "$MASDir"
`$ServiceScript = "$ServiceScript"
`$LogFile = "$LogFile"

# Ensure log directory exists
`$LogDir = Split-Path `$LogFile -Parent
if (-not (Test-Path `$LogDir)) {
    New-Item -ItemType Directory -Path `$LogDir -Force | Out-Null
}

# Change to project directory
Set-Location `$MASDir

# Check if service is already running
`$existing = Get-Process python -ErrorAction SilentlyContinue | Where-Object {
    try {
        `$cmd = (Get-CimInstance Win32_Process -Filter "ProcessId = `$(`$_.Id)").CommandLine
        `$cmd -like "*mycobrain_service*"
    } catch {
        `$false
    }
}

if (`$existing) {
    Add-Content -Path `$LogFile -Value "[`$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] MycoBrain service already running (PID: `$(`$existing.Id -join ', '))"
    exit 0
}

# Start service in background
Add-Content -Path `$LogFile -Value "[`$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] Starting MycoBrain service..."
`$psCommand = "Set-Location '`$MASDir'; python `"`$ServiceScript`" 2>&1 | Tee-Object -FilePath '`$LogFile' -Append"
Start-Process powershell.exe -ArgumentList "-NoProfile", "-WindowStyle Hidden", "-Command", `$psCommand

# Wait a moment for service to start
Start-Sleep -Seconds 5

# Verify service is running
`$running = Get-Process python -ErrorAction SilentlyContinue | Where-Object {
    try {
        `$cmd = (Get-CimInstance Win32_Process -Filter "ProcessId = `$(`$_.Id)").CommandLine
        `$cmd -like "*mycobrain_service*"
    } catch {
        `$false
    }
}

if (`$running) {
    Add-Content -Path `$LogFile -Value "[`$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] MycoBrain service started successfully (PID: `$(`$running.Id -join ', '))"
} else {
    Add-Content -Path `$LogFile -Value "[`$(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')] WARNING: MycoBrain service may not have started. Check logs."
}
"@

$WrapperContent | Out-File -FilePath $WrapperScript -Encoding UTF8
Write-Host "Created wrapper script: $WrapperScript" -ForegroundColor Gray

# Create action - run PowerShell with the wrapper script
$action = New-ScheduledTaskAction `
    -Execute "powershell.exe" `
    -Argument "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$WrapperScript`"" `
    -WorkingDirectory $MASDir

# Create triggers:
# 1. At system startup (for services)
# 2. At user logon (backup)
$triggerStartup = New-ScheduledTaskTrigger -AtStartup
$triggerLogon = New-ScheduledTaskTrigger -AtLogOn

# Add a delay to startup trigger to ensure USB/COM ports are ready
$triggerStartup.Delay = "PT60S"  # 60 second delay

# Settings for the task
$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -StartWhenAvailable `
    -RunOnlyIfNetworkAvailable:$false `
    -MultipleInstances IgnoreNew `
    -RestartCount 3 `
    -RestartInterval (New-TimeSpan -Minutes 2)

# Principal - run with highest privileges
$principal = New-ScheduledTaskPrincipal `
    -UserId "$env:USERDOMAIN\$env:USERNAME" `
    -LogonType Interactive `
    -RunLevel Highest

# Register the task
try {
    Register-ScheduledTask `
        -TaskName $TaskName `
        -Action $action `
        -Trigger @($triggerStartup, $triggerLogon) `
        -Settings $settings `
        -Principal $principal `
        -Description "Automatically starts MycoBrain service on Windows startup. Connects to COM7 ESP32-S3 device and serves on port 8003. Includes 60-second delay to wait for USB/COM ports." `
        -Force | Out-Null
    
    Write-Host ""
    Write-Host "============================================" -ForegroundColor Green
    Write-Host "  Task installed successfully!" -ForegroundColor Green
    Write-Host "============================================" -ForegroundColor Green
    Write-Host ""
    Write-Host "Task Name: $TaskName" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "The task will run:" -ForegroundColor White
    Write-Host "  - 60 seconds after Windows starts (to wait for USB/COM ports)" -ForegroundColor Gray
    Write-Host "  - When you log in (backup trigger)" -ForegroundColor Gray
    Write-Host ""
    Write-Host "What it does:" -ForegroundColor White
    Write-Host "  1. Waits for USB/COM ports to be available" -ForegroundColor Gray
    Write-Host "  2. Starts MycoBrain service on port 8003" -ForegroundColor Gray
    Write-Host "  3. Connects to ESP32-S3 device on COM7" -ForegroundColor Gray
    Write-Host "  4. Makes device accessible to sandbox.mycosoft.com" -ForegroundColor Gray
    Write-Host ""
    Write-Host "Service URL: http://192.168.0.172:8003" -ForegroundColor Cyan
    Write-Host "Log file: $LogFile" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "To verify the task:" -ForegroundColor Yellow
    Write-Host "  Get-ScheduledTask -TaskName '$TaskName' | Format-List" -ForegroundColor White
    Write-Host ""
    Write-Host "To test now (without restarting):" -ForegroundColor Yellow
    Write-Host "  Start-ScheduledTask -TaskName '$TaskName'" -ForegroundColor White
    Write-Host ""
    Write-Host "To check service status:" -ForegroundColor Yellow
    Write-Host "  curl.exe http://localhost:8003/health" -ForegroundColor White
    Write-Host ""
    Write-Host "To view logs:" -ForegroundColor Yellow
    Write-Host "  Get-Content '$LogFile' -Tail 50 -Wait" -ForegroundColor White
    Write-Host ""
    Write-Host "To remove the task:" -ForegroundColor Yellow
    Write-Host "  .\scripts\install-mycobrain-autostart.ps1 -Remove" -ForegroundColor White
    
} catch {
    Write-Host "Error installing task: $_" -ForegroundColor Red
    exit 1
}
