# MycoBrain Remote Setup Script
# For setting up MycoBrain on remote machines (e.g., Beto's PC)
# Created: February 10, 2026

param(
    [string]$DeviceName = "Remote MycoBrain",
    [string]$Location = "Remote Lab",
    [switch]$InstallTailscale,
    [switch]$StartService,
    [string]$MasRegistryUrl = "http://192.168.0.188:8001",
    [int]$ServicePort = 8003
)

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "   MycoBrain Remote Setup Script" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Check if running as administrator for Tailscale install
$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

# Step 1: Install Tailscale (optional)
if ($InstallTailscale) {
    Write-Host "[1/5] Installing Tailscale..." -ForegroundColor Yellow
    
    if (-not $isAdmin) {
        Write-Host "  WARNING: Administrator privileges required for Tailscale install" -ForegroundColor Red
        Write-Host "  Run this script as Administrator, or install Tailscale manually:" -ForegroundColor Yellow
        Write-Host "  https://tailscale.com/download/windows" -ForegroundColor Gray
    } else {
        try {
            # Download and install Tailscale
            $tailscaleInstaller = "$env:TEMP\tailscale-setup.exe"
            Write-Host "  Downloading Tailscale installer..."
            Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile $tailscaleInstaller
            
            Write-Host "  Running installer..."
            Start-Process -FilePath $tailscaleInstaller -ArgumentList "/quiet" -Wait
            
            Write-Host "  Tailscale installed!" -ForegroundColor Green
            Write-Host ""
            Write-Host "  IMPORTANT: Run 'tailscale up' and sign in to join the Mycosoft Tailnet" -ForegroundColor Cyan
        } catch {
            Write-Host "  Failed to install Tailscale: $_" -ForegroundColor Red
            Write-Host "  Install manually from: https://tailscale.com/download/windows" -ForegroundColor Yellow
        }
    }
} else {
    Write-Host "[1/5] Tailscale install skipped (use -InstallTailscale to install)" -ForegroundColor Gray
}
Write-Host ""

# Step 2: Check Python
Write-Host "[2/5] Checking Python installation..." -ForegroundColor Yellow
$pythonVersion = python --version 2>&1
if ($LASTEXITCODE -eq 0) {
    Write-Host "  $pythonVersion" -ForegroundColor Green
} else {
    Write-Host "  Python not found!" -ForegroundColor Red
    Write-Host "  Please install Python 3.10+ from https://python.org" -ForegroundColor Yellow
    exit 1
}
Write-Host ""

# Step 3: Clone or update repo
Write-Host "[3/5] Setting up MycoBrain service..." -ForegroundColor Yellow
$repoPath = "$env:USERPROFILE\mycosoft-mas"
$serviceDir = "$repoPath\services\mycobrain"

if (Test-Path $repoPath) {
    Write-Host "  Repository found at $repoPath" -ForegroundColor Green
    Write-Host "  Updating..."
    Push-Location $repoPath
    git pull origin main 2>&1 | Out-Null
    Pop-Location
} else {
    Write-Host "  Cloning repository..."
    git clone https://github.com/mycosoft/mycosoft-mas.git $repoPath 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) {
        Write-Host "  Failed to clone repository!" -ForegroundColor Red
        Write-Host "  Ensure you have Git installed and GitHub access" -ForegroundColor Yellow
        exit 1
    }
}
Write-Host "  Repository ready!" -ForegroundColor Green
Write-Host ""

# Step 4: Install dependencies
Write-Host "[4/5] Installing Python dependencies..." -ForegroundColor Yellow
Push-Location $serviceDir
pip install -q fastapi uvicorn pyserial httpx psutil 2>&1 | Out-Null
if ($LASTEXITCODE -eq 0) {
    Write-Host "  Dependencies installed!" -ForegroundColor Green
} else {
    Write-Host "  Warning: Some dependencies may have failed to install" -ForegroundColor Yellow
}
Pop-Location
Write-Host ""

# Step 5: Configure environment
Write-Host "[5/5] Configuring environment..." -ForegroundColor Yellow

# Detect Tailscale IP
$tailscaleIp = $null
try {
    $tailscaleIp = (tailscale ip -4 2>$null).Trim()
    if ($tailscaleIp -and $tailscaleIp.StartsWith("100.")) {
        Write-Host "  Tailscale IP detected: $tailscaleIp" -ForegroundColor Green
    }
} catch {
    Write-Host "  Tailscale IP not detected (Tailscale may not be running)" -ForegroundColor Yellow
}

# Create/update .env file
$envPath = "$serviceDir\.env"
$envContent = @"
# MycoBrain Remote Configuration
# Generated by mycobrain-remote-setup.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

# Device identification
MYCOBRAIN_DEVICE_NAME=$DeviceName
MYCOBRAIN_DEVICE_LOCATION=$Location

# MAS Registry for heartbeat
MAS_REGISTRY_URL=$MasRegistryUrl

# Heartbeat settings
MYCOBRAIN_HEARTBEAT_ENABLED=true
MYCOBRAIN_HEARTBEAT_INTERVAL=30

# Service port
MYCOBRAIN_SERVICE_PORT=$ServicePort

# Tailscale IP (if available)
$(if ($tailscaleIp) { "MYCOBRAIN_PUBLIC_HOST=$tailscaleIp" } else { "# MYCOBRAIN_PUBLIC_HOST=  # Set manually if using Tailscale or Cloudflare" })
"@

Set-Content -Path $envPath -Value $envContent
Write-Host "  Environment file created: $envPath" -ForegroundColor Green

# Display configuration
Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "   Configuration Summary" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Device Name:     $DeviceName" -ForegroundColor White
Write-Host "  Location:        $Location" -ForegroundColor White
Write-Host "  MAS Registry:    $MasRegistryUrl" -ForegroundColor White
Write-Host "  Service Port:    $ServicePort" -ForegroundColor White
if ($tailscaleIp) {
    Write-Host "  Tailscale IP:    $tailscaleIp" -ForegroundColor White
}
Write-Host ""

# Step 6: Start service (optional)
if ($StartService) {
    Write-Host "Starting MycoBrain service..." -ForegroundColor Yellow
    Push-Location $serviceDir
    
    # Load .env file
    Get-Content .env | ForEach-Object {
        if ($_ -match '^([^#][^=]*)=(.*)$') {
            [Environment]::SetEnvironmentVariable($matches[1].Trim(), $matches[2].Trim(), "Process")
        }
    }
    
    Write-Host "  Service starting on port $ServicePort..."
    Start-Process python -ArgumentList "mycobrain_service_standalone.py" -NoNewWindow
    
    Start-Sleep -Seconds 3
    
    # Check if running
    $proc = Get-Process python -ErrorAction SilentlyContinue | Where-Object { $_.CommandLine -like "*mycobrain*" }
    if ($proc) {
        Write-Host "  Service started successfully!" -ForegroundColor Green
        Write-Host ""
        Write-Host "  Device should appear in MAS Device Manager within 30 seconds" -ForegroundColor Cyan
    } else {
        Write-Host "  Service may have failed to start. Check the console output." -ForegroundColor Yellow
    }
    
    Pop-Location
} else {
    Write-Host "To start the service manually:" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "  cd $serviceDir" -ForegroundColor Gray
    Write-Host "  python mycobrain_service_standalone.py" -ForegroundColor Gray
    Write-Host ""
}

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "   Setup Complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Yellow
Write-Host "  1. Connect your MycoBrain device via USB" -ForegroundColor White
Write-Host "  2. Start the service (if not already running)" -ForegroundColor White
Write-Host "  3. Check the Device Manager on mycosoft.com for your device" -ForegroundColor White
Write-Host ""
Write-Host "For help, see: docs/MYCOBRAIN_TAILSCALE_SETUP_FEB10_2026.md" -ForegroundColor Gray
