# Python package dependencies
python_packages:
  selenium: ">=4.0.0"
  pyautogui: ">=0.9.53"
  pywinauto: ">=0.6.8"
  undetected-chromedriver: ">=3.5.0"
  aiohttp: ">=3.8.0"
  fastapi: ">=0.68.0"
  pydantic: ">=1.8.0"
  prometheus-client: ">=0.12.0"
  python-dotenv: ">=0.19.0"
  yaml: ">=5.4.1"
  semver: ">=2.13.0"

# Agent dependencies
agent_dependencies:
  research_agent:
    - data_analysis
    - web_scraping
    - document_processing
  finance_agent:
    - accounting
    - transaction_processing
    - report_generation
  project_management_agent:
    - task_tracking
    - resource_management
    - timeline_planning
  desktop_automation_agent:
    - browser_automation
    - desktop_control
    - input_simulation 